##############################
#
#
##############################

export G4DATA=/usr/local/share/Geant4-10.7.2/data

export G4NEUTRONHPDATA=${G4DATA}/G4NDL4.6
export G4PARTICLEHPDATA=${G4DATA}/G4TENDL1.3.2
#export G4LEDATA=${G4DATA}/G4EMLOW7.9.1

#unset G4NEUTRONHP_SKIP_MISSING_ISOTOPES 
#unset G4NEUTRONHP_DO_NOT_ADJUST_FINAL_STATE
#unset G4NEUTRONHP_USE_ONLY_PHOTONEVAPORATION
#unset G4NEUTRONHP_NEGLECT_DOPPLER
#unset G4NEUTRONHP_PRODUCE_FISSION_FRAGMENTS

 #G4NEUTRONHP_SKIP_MISSING_ISOTOPES=1
 #export G4NEUTRONHP_SKIP_MISSING_ISOTOPES

 #G4NEUTRONHP_DO_NOT_ADJUST_FINAL_STATE=1
 #export G4NEUTRONHP_DO_NOT_ADJUST_FINAL_STATE
 
 #AllowForHeavyElements=1
 #export AllowForHeavyElements
  
#### G4NEUTRONHP_USE_ONLY_PHOTONEVAPORATION=1
#### export G4NEUTRONHP_USE_ONLY_PHOTONEVAPORATION
  
 #G4NEUTRONHP_NEGLECT_DOPPLER=1
 #export G4NEUTRONHP_NEGLECT_DOPPLER
  
 #G4NEUTRONHP_PRODUCE_FISSION_FRAGMENTS=0
 #export G4NEUTRONHP_PRODUCE_FISSION_FRAGMENTS

#
# for Bertini cascade
#
#unset G4CASCADE_USE_PRECOMPOUND  
#G4CASCADE_USE_PRECOMPOUND=1
#export G4CASCADE_USE_PRECOMPOUND             

env |grep G4NEUTRONHP
env |grep G4PARTICLEHPDATA
