####
#### 40Ar beam
####

/tracking/verbose 0
/event/verbose 0
/run/initialize
/run/printProgress 20000000

/gps/particle ion
/gps/ion 18 40 14 0 

/gps/pos/type Plane      
/gps/pos/shape Circle
/gps/pos/radius 0.5 mm
/gps/pos/centre 0.0 0.0 -5.0 cm
/gps/ang/type iso
/gps/direction 0 0 1

/gps/ene/type Gauss

/gps/energy 102.0 MeV
/gps/ene/sigma 4.4357 MeV 

#sigma is calculated as sigma=Eloss(centerTarget)/2.355 (FWHM = 2.355*sigma)

/run/beamOn 100000000