#control the physics

/control/verbose 0
/tracking/verbose 0
/event/verbose 0


/run/numberOfThreads 4
/run/initialize
/run/printProgress 20000000

#/process/had/particle_hp/skip_missing_isotopes true
#/process/had/particle_hp/do_not_adjust_final_state true
#/process/had/particle_hp/neglect_Doppler_broadening true
#/process/had/particle_hp/produce_fission_fragment true
#/process/had/particle_hp/verbose 2

#/control/execute cobalt.mac
/run/beamOn 100000000